# Generated by Django 5.2.17 on 2026-09-15 15:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='ครบกำหนดชำระ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='เครดิต (วัน)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='ลิงก์รูปสินค้า (HTTPS)'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.PositiveBigIntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ราคาเฉพาะลูกค้าต่อหน่วย')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='shop.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='shop.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'customer'), name='unique_customer_product_price')],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='จำนวนรวมต่อรุ่นตั้งแต่')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ราคาต่อหน่วย')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='shop.product')),
            ],
            options={
                'ordering': ['minimum_quantity'],
                'constraints': [models.UniqueConstraint(fields=('product', 'minimum_quantity'), name='unique_product_tier')],
            },
        ),
    ]
