# Generated by Django 5.2.17 on 2026-09-17 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bill_due_date_customer_credit_days_product_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.customer')),
                ('payments', models.ManyToManyField(related_name='bundles', to='shop.payment')),
            ],
        ),
    ]
